version: '3.8'

services:
    minio:
        image: minio/minio:latest
        container_name: minio
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - data:/data
        environment:
            - "MINIO_ROOT_USER=minioadmin"
            - "MINIO_ROOT_PASSWORD=minioadmin"
        command: server /data --console-address :9001
    createbucket:
        image: minio/mc:latest
        depends_on:
            - minio
        entrypoint: >
            /bin/sh -c "
            /usr/bin/mc config host add --api s3v4 s3 http://minio:9000 minioadmin minioadmin;
            /usr/bin/mc mb s3/media/;
            /usr/bin/mc anonymous set download s3/media;
            "

    web:
        build: .
        entrypoint: >
            /bin/sh -c "python3 manage.py collectstatic --no-input;
            python manage.py migrate;
            gunicorn settings.wsgi:application --bind 0.0.0.0:8000;
            "
        volumes:
            - ./:/usr/src/app/
            - static_volume:/usr/src/app/staticfiles
            - media_volume:/usr/src/app/media
        expose:
            - 8000
        env_file:
            - .env.docker
        depends_on:
            - db
            - minio
            - createbucket
        extra_hosts:
            - "host.docker.internal:host-gateway"
    db:
        image: postgres:16
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=hello_django
            - POSTGRES_PASSWORD=hello_django
            - POSTGRES_DB=voip
    nginx:
        build: ./nginx
        ports:
            - 8687:80
        volumes:
            - static_volume:/usr/src/app/staticfiles
            - media_volume:/usr/src/app/media
        depends_on:
            - web
        restart: "always"
volumes:
    postgres_data:
    data:
    static_volume:
    media_volume:
    