version: '3.9'

services:
  rental:
    build: .
    command: uvicorn settings.asgi:application --host 0.0.0.0 --port 8000 --access-log --use-colors --log-level trace
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
