

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."auditlog_logentry" (
    "id" integer NOT NULL,
    "object_pk" character varying(255) NOT NULL,
    "object_id" bigint,
    "object_repr" "text" NOT NULL,
    "action" smallint NOT NULL,
    "changes" "jsonb",
    "timestamp" timestamp with time zone NOT NULL,
    "actor_id" bigint,
    "content_type_id" integer NOT NULL,
    "remote_addr" "inet",
    "additional_data" "jsonb",
    "serialized_data" "jsonb",
    "cid" character varying(255),
    "changes_text" "text" NOT NULL,
    CONSTRAINT "auditlog_logentry_action_check" CHECK (("action" >= 0))
);


ALTER TABLE "public"."auditlog_logentry" OWNER TO "postgres";


ALTER TABLE "public"."auditlog_logentry" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auditlog_logentry_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auth_group" (
    "id" integer NOT NULL,
    "name" character varying(150) NOT NULL
);


ALTER TABLE "public"."auth_group" OWNER TO "postgres";


ALTER TABLE "public"."auth_group" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_group_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auth_group_permissions" (
    "id" bigint NOT NULL,
    "group_id" integer NOT NULL,
    "permission_id" integer NOT NULL
);


ALTER TABLE "public"."auth_group_permissions" OWNER TO "postgres";


ALTER TABLE "public"."auth_group_permissions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_group_permissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auth_permission" (
    "id" integer NOT NULL,
    "name" character varying(255) NOT NULL,
    "content_type_id" integer NOT NULL,
    "codename" character varying(100) NOT NULL
);


ALTER TABLE "public"."auth_permission" OWNER TO "postgres";


ALTER TABLE "public"."auth_permission" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_permission_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_admin_log" (
    "id" integer NOT NULL,
    "action_time" timestamp with time zone NOT NULL,
    "object_id" "text",
    "object_repr" character varying(200) NOT NULL,
    "action_flag" smallint NOT NULL,
    "change_message" "text" NOT NULL,
    "content_type_id" integer,
    "user_id" bigint NOT NULL,
    CONSTRAINT "django_admin_log_action_flag_check" CHECK (("action_flag" >= 0))
);


ALTER TABLE "public"."django_admin_log" OWNER TO "postgres";


ALTER TABLE "public"."django_admin_log" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_admin_log_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_content_type" (
    "id" integer NOT NULL,
    "app_label" character varying(100) NOT NULL,
    "model" character varying(100) NOT NULL
);


ALTER TABLE "public"."django_content_type" OWNER TO "postgres";


ALTER TABLE "public"."django_content_type" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_content_type_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_migrations" (
    "id" bigint NOT NULL,
    "app" character varying(255) NOT NULL,
    "name" character varying(255) NOT NULL,
    "applied" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."django_migrations" OWNER TO "postgres";


ALTER TABLE "public"."django_migrations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_migrations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_seeding_appliedseeder" (
    "id" character varying(100) NOT NULL
);


ALTER TABLE "public"."django_seeding_appliedseeder" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."django_session" (
    "session_key" character varying(40) NOT NULL,
    "session_data" "text" NOT NULL,
    "expire_date" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."django_session" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."rental_card" (
    "id" bigint NOT NULL,
    "name" character varying(255) NOT NULL,
    "form_id" bigint NOT NULL
);


ALTER TABLE "public"."rental_card" OWNER TO "postgres";


ALTER TABLE "public"."rental_card" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_card_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_checkoption" (
    "id" bigint NOT NULL,
    "name" character varying(255) NOT NULL,
    "field_id" bigint NOT NULL,
    "type" character varying(20) NOT NULL
);


ALTER TABLE "public"."rental_checkoption" OWNER TO "postgres";


ALTER TABLE "public"."rental_checkoption" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_checkoption_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_client" (
    "id" bigint NOT NULL,
    "name" character varying(255) NOT NULL,
    "email" character varying(254) NOT NULL,
    "phone_number" character varying(255) NOT NULL,
    "tenant_id" bigint NOT NULL
);


ALTER TABLE "public"."rental_client" OWNER TO "postgres";


ALTER TABLE "public"."rental_client" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_client_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_contract" (
    "id" bigint NOT NULL,
    "creation_date" timestamp with time zone NOT NULL,
    "active_date" timestamp with time zone,
    "end_date" timestamp with time zone,
    "client_id" bigint NOT NULL,
    "tenant_id" bigint NOT NULL,
    "vehicle_id" bigint NOT NULL,
    "rental_plan_id" bigint NOT NULL
);


ALTER TABLE "public"."rental_contract" OWNER TO "postgres";


ALTER TABLE "public"."rental_contract" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_contract_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_contractform" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "name" character varying(255) NOT NULL,
    "template_id" bigint NOT NULL,
    "tenant_id" bigint NOT NULL,
    "user_id" bigint NOT NULL
);


ALTER TABLE "public"."rental_contractform" OWNER TO "postgres";


ALTER TABLE "public"."rental_contractform" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_contractform_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_contractformfield" (
    "id" bigint NOT NULL,
    "placeholder" character varying(255) NOT NULL,
    "type" character varying(20) NOT NULL,
    "required" boolean NOT NULL,
    "template_id" bigint NOT NULL
);


ALTER TABLE "public"."rental_contractformfield" OWNER TO "postgres";


ALTER TABLE "public"."rental_contractformfield" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_contractformfield_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_contractformfieldresponse" (
    "id" bigint NOT NULL,
    "content" character varying(300) NOT NULL,
    "field_id" bigint NOT NULL,
    "form_id" bigint NOT NULL
);


ALTER TABLE "public"."rental_contractformfieldresponse" OWNER TO "postgres";


ALTER TABLE "public"."rental_contractformfieldresponse" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_contractformfieldresponse_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_contractformtemplate" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "template" "jsonb",
    "is_active" boolean NOT NULL,
    "name" character varying(255) NOT NULL,
    "tenant_id" bigint NOT NULL,
    "user_id" bigint NOT NULL
);


ALTER TABLE "public"."rental_contractformtemplate" OWNER TO "postgres";


ALTER TABLE "public"."rental_contractformtemplate" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_contractformtemplate_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_field" (
    "id" bigint NOT NULL,
    "name" character varying(255) NOT NULL,
    "required" boolean NOT NULL,
    "type" character varying(20) NOT NULL,
    "card_id" bigint
);


ALTER TABLE "public"."rental_field" OWNER TO "postgres";


ALTER TABLE "public"."rental_field" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_field_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_fieldresponse" (
    "id" bigint NOT NULL,
    "note" "text",
    "created_at" timestamp with time zone NOT NULL,
    "content" "text",
    "check_option_selected_id" bigint,
    "field_id" bigint NOT NULL,
    "tenantUser_id" bigint NOT NULL,
    "inspection_id" bigint
);


ALTER TABLE "public"."rental_fieldresponse" OWNER TO "postgres";


ALTER TABLE "public"."rental_fieldresponse" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_fieldresponse_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_form" (
    "id" bigint NOT NULL,
    "name" character varying(255) NOT NULL,
    "is_active" boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "tenant_id" bigint NOT NULL
);


ALTER TABLE "public"."rental_form" OWNER TO "postgres";


ALTER TABLE "public"."rental_form" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_form_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_inspection" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "form_id" bigint NOT NULL,
    "tenant_id" bigint NOT NULL,
    "tenantUser_id" bigint NOT NULL,
    "vehicle_id" bigint NOT NULL
);


ALTER TABLE "public"."rental_inspection" OWNER TO "postgres";


ALTER TABLE "public"."rental_inspection" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_inspection_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_note" (
    "id" bigint NOT NULL,
    "subject" character varying(255) NOT NULL,
    "body" "text" NOT NULL,
    "createdDate" timestamp with time zone NOT NULL,
    "remainder" timestamp with time zone,
    "file" character varying(100),
    "contract_id" bigint NOT NULL,
    "user_id" bigint NOT NULL
);


ALTER TABLE "public"."rental_note" OWNER TO "postgres";


ALTER TABLE "public"."rental_note" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_note_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_reminder" (
    "id" bigint NOT NULL,
    "status" character varying(50) NOT NULL,
    "important" boolean NOT NULL,
    "title" "text" NOT NULL,
    "content" "text",
    "remainder" timestamp with time zone,
    "file" character varying(100),
    "created_at" timestamp with time zone NOT NULL,
    "client_id" bigint,
    "contract_id" bigint,
    "created_by_id" bigint,
    "toll_due_id" bigint,
    "vehicle_id" bigint,
    "reminder_id" bigint
);


ALTER TABLE "public"."rental_reminder" OWNER TO "postgres";


ALTER TABLE "public"."rental_reminder" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_reminder_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_rentalplan" (
    "id" bigint NOT NULL,
    "name" character varying(255) NOT NULL,
    "amount" integer NOT NULL,
    "periodicity" character varying(10) NOT NULL,
    "tenant_id" bigint NOT NULL
);


ALTER TABLE "public"."rental_rentalplan" OWNER TO "postgres";


ALTER TABLE "public"."rental_rentalplan" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_rentalplan_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_stageupdate" (
    "id" bigint NOT NULL,
    "date" timestamp with time zone NOT NULL,
    "reason" character varying(255),
    "comments" character varying(255),
    "stage" character varying(100) NOT NULL,
    "contract_id" bigint NOT NULL
);


ALTER TABLE "public"."rental_stageupdate" OWNER TO "postgres";


ALTER TABLE "public"."rental_stageupdate" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_stageupdate_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_tenant" (
    "id" bigint NOT NULL,
    "email" character varying(254) NOT NULL,
    "name" character varying(100) NOT NULL,
    "isAdmin" boolean NOT NULL,
    "date_joined" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."rental_tenant" OWNER TO "postgres";


ALTER TABLE "public"."rental_tenant" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_tenant_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_tenantuser" (
    "id" bigint NOT NULL,
    "role" character varying(10) NOT NULL,
    "is_default" boolean NOT NULL,
    "tenant_id" bigint NOT NULL,
    "user_id" bigint NOT NULL
);


ALTER TABLE "public"."rental_tenantuser" OWNER TO "postgres";


ALTER TABLE "public"."rental_tenantuser" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_tenantuser_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_tolldue" (
    "id" bigint NOT NULL,
    "amount" integer NOT NULL,
    "stage" character varying(6) NOT NULL,
    "invoice" character varying(255),
    "invoiceNumber" character varying(255),
    "createDate" timestamp with time zone NOT NULL,
    "note" "text",
    "contract_id" bigint NOT NULL,
    "plate_id" bigint NOT NULL
);


ALTER TABLE "public"."rental_tolldue" OWNER TO "postgres";


ALTER TABLE "public"."rental_tolldue" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_tolldue_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_tracker" (
    "id" bigint NOT NULL,
    "name" character varying(255) NOT NULL,
    "created_date" timestamp with time zone NOT NULL,
    "vehicle_id" bigint NOT NULL
);


ALTER TABLE "public"."rental_tracker" OWNER TO "postgres";


ALTER TABLE "public"."rental_tracker" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_tracker_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_trackerheartbeatdata" (
    "id" bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    "latitude" double precision NOT NULL,
    "longitude" double precision NOT NULL,
    "tracker_id" bigint NOT NULL
);


ALTER TABLE "public"."rental_trackerheartbeatdata" OWNER TO "postgres";


ALTER TABLE "public"."rental_trackerheartbeatdata" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_trackerheartbeatdata_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_user" (
    "id" bigint NOT NULL,
    "password" character varying(128) NOT NULL,
    "last_login" timestamp with time zone,
    "email" character varying(254) NOT NULL,
    "image" character varying(100),
    "date_joined" timestamp with time zone NOT NULL,
    "is_active" boolean NOT NULL,
    "is_staff" boolean NOT NULL,
    "is_superuser" boolean NOT NULL,
    "name" character varying(100) NOT NULL
);


ALTER TABLE "public"."rental_user" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."rental_user_groups" (
    "id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "group_id" integer NOT NULL
);


ALTER TABLE "public"."rental_user_groups" OWNER TO "postgres";


ALTER TABLE "public"."rental_user_groups" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_user_groups_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."rental_user" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_user_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_user_user_permissions" (
    "id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "permission_id" integer NOT NULL
);


ALTER TABLE "public"."rental_user_user_permissions" OWNER TO "postgres";


ALTER TABLE "public"."rental_user_user_permissions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_user_user_permissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_vehicle" (
    "id" bigint NOT NULL,
    "type" character varying NOT NULL,
    "year" integer,
    "make" character varying(255),
    "trim" character varying(255),
    "vin" character varying(17) NOT NULL,
    "odometer" integer,
    "nickname" character varying(255),
    "spare_tires" integer,
    "extra_fields" "jsonb",
    "status" character varying NOT NULL,
    "tenant_id" bigint NOT NULL,
    "model" character varying(255),
    "is_deleted" boolean NOT NULL
);


ALTER TABLE "public"."rental_vehicle" OWNER TO "postgres";


ALTER TABLE "public"."rental_vehicle" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_vehicle_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_vehiclepicture" (
    "id" bigint NOT NULL,
    "image" character varying(100) NOT NULL,
    "pinned" boolean NOT NULL,
    "vehicle_id" bigint NOT NULL
);


ALTER TABLE "public"."rental_vehiclepicture" OWNER TO "postgres";


ALTER TABLE "public"."rental_vehiclepicture" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_vehiclepicture_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rental_vehicleplate" (
    "id" bigint NOT NULL,
    "is_active" boolean NOT NULL,
    "plate" character varying(255) NOT NULL,
    "assign_date" timestamp with time zone NOT NULL,
    "dismiss_date" timestamp with time zone,
    "vehicle_id" bigint NOT NULL
);


ALTER TABLE "public"."rental_vehicleplate" OWNER TO "postgres";


ALTER TABLE "public"."rental_vehicleplate" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rental_vehicleplate_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."token_blacklist_blacklistedtoken" (
    "id" bigint NOT NULL,
    "blacklisted_at" timestamp with time zone NOT NULL,
    "token_id" bigint NOT NULL
);


ALTER TABLE "public"."token_blacklist_blacklistedtoken" OWNER TO "postgres";


ALTER TABLE "public"."token_blacklist_blacklistedtoken" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."token_blacklist_blacklistedtoken_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."token_blacklist_outstandingtoken" (
    "id" bigint NOT NULL,
    "token" "text" NOT NULL,
    "created_at" timestamp with time zone,
    "expires_at" timestamp with time zone NOT NULL,
    "user_id" bigint,
    "jti" character varying(255) NOT NULL
);


ALTER TABLE "public"."token_blacklist_outstandingtoken" OWNER TO "postgres";


ALTER TABLE "public"."token_blacklist_outstandingtoken" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."token_blacklist_outstandingtoken_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."auditlog_logentry"
    ADD CONSTRAINT "auditlog_logentry_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_group"
    ADD CONSTRAINT "auth_group_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id");



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_group"
    ADD CONSTRAINT "auth_group_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_permission"
    ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename");



ALTER TABLE ONLY "public"."auth_permission"
    ADD CONSTRAINT "auth_permission_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_admin_log"
    ADD CONSTRAINT "django_admin_log_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_content_type"
    ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model");



ALTER TABLE ONLY "public"."django_content_type"
    ADD CONSTRAINT "django_content_type_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_migrations"
    ADD CONSTRAINT "django_migrations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_seeding_appliedseeder"
    ADD CONSTRAINT "django_seeding_appliedseeder_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_session"
    ADD CONSTRAINT "django_session_pkey" PRIMARY KEY ("session_key");



ALTER TABLE ONLY "public"."rental_card"
    ADD CONSTRAINT "rental_card_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_checkoption"
    ADD CONSTRAINT "rental_checkoption_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_client"
    ADD CONSTRAINT "rental_client_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."rental_client"
    ADD CONSTRAINT "rental_client_phone_number_key" UNIQUE ("phone_number");



ALTER TABLE ONLY "public"."rental_client"
    ADD CONSTRAINT "rental_client_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_contract"
    ADD CONSTRAINT "rental_contract_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_contractform"
    ADD CONSTRAINT "rental_contractform_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_contractformfield"
    ADD CONSTRAINT "rental_contractformfield_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_contractformfieldresponse"
    ADD CONSTRAINT "rental_contractformfieldresponse_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_contractformtemplate"
    ADD CONSTRAINT "rental_contractformtemplate_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_field"
    ADD CONSTRAINT "rental_field_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_fieldresponse"
    ADD CONSTRAINT "rental_fieldresponse_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_form"
    ADD CONSTRAINT "rental_form_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_inspection"
    ADD CONSTRAINT "rental_inspection_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_note"
    ADD CONSTRAINT "rental_note_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_reminder"
    ADD CONSTRAINT "rental_reminder_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_rentalplan"
    ADD CONSTRAINT "rental_rentalplan_name_periodicity_amount__9419643b_uniq" UNIQUE ("name", "periodicity", "amount", "tenant_id");



ALTER TABLE ONLY "public"."rental_rentalplan"
    ADD CONSTRAINT "rental_rentalplan_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_stageupdate"
    ADD CONSTRAINT "rental_stageupdate_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_tenant"
    ADD CONSTRAINT "rental_tenant_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."rental_tenant"
    ADD CONSTRAINT "rental_tenant_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_tenantuser"
    ADD CONSTRAINT "rental_tenantuser_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_tolldue"
    ADD CONSTRAINT "rental_tolldue_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_tracker"
    ADD CONSTRAINT "rental_tracker_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_tracker"
    ADD CONSTRAINT "rental_tracker_vehicle_id_49a19b0e_uniq" UNIQUE ("vehicle_id");



ALTER TABLE ONLY "public"."rental_trackerheartbeatdata"
    ADD CONSTRAINT "rental_trackerheartbeatdata_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_user"
    ADD CONSTRAINT "rental_user_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."rental_user_groups"
    ADD CONSTRAINT "rental_user_groups_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_user_groups"
    ADD CONSTRAINT "rental_user_groups_user_id_group_id_d509a6bd_uniq" UNIQUE ("user_id", "group_id");



ALTER TABLE ONLY "public"."rental_user"
    ADD CONSTRAINT "rental_user_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_user_user_permissions"
    ADD CONSTRAINT "rental_user_user_permiss_user_id_permission_id_fef91321_uniq" UNIQUE ("user_id", "permission_id");



ALTER TABLE ONLY "public"."rental_user_user_permissions"
    ADD CONSTRAINT "rental_user_user_permissions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_vehicle"
    ADD CONSTRAINT "rental_vehicle_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_vehicle"
    ADD CONSTRAINT "rental_vehicle_vin_key" UNIQUE ("vin");



ALTER TABLE ONLY "public"."rental_vehiclepicture"
    ADD CONSTRAINT "rental_vehiclepicture_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_vehicleplate"
    ADD CONSTRAINT "rental_vehicleplate_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rental_vehicleplate"
    ADD CONSTRAINT "rental_vehicleplate_plate_key" UNIQUE ("plate");



ALTER TABLE ONLY "public"."token_blacklist_blacklistedtoken"
    ADD CONSTRAINT "token_blacklist_blacklistedtoken_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."token_blacklist_blacklistedtoken"
    ADD CONSTRAINT "token_blacklist_blacklistedtoken_token_id_key" UNIQUE ("token_id");



ALTER TABLE ONLY "public"."token_blacklist_outstandingtoken"
    ADD CONSTRAINT "token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq" UNIQUE ("jti");



ALTER TABLE ONLY "public"."token_blacklist_outstandingtoken"
    ADD CONSTRAINT "token_blacklist_outstandingtoken_pkey" PRIMARY KEY ("id");



CREATE INDEX "auditlog_logentry_action_229afe39" ON "public"."auditlog_logentry" USING "btree" ("action");



CREATE INDEX "auditlog_logentry_actor_id_959271d2" ON "public"."auditlog_logentry" USING "btree" ("actor_id");



CREATE INDEX "auditlog_logentry_cid_9f467263" ON "public"."auditlog_logentry" USING "btree" ("cid");



CREATE INDEX "auditlog_logentry_cid_9f467263_like" ON "public"."auditlog_logentry" USING "btree" ("cid" "varchar_pattern_ops");



CREATE INDEX "auditlog_logentry_content_type_id_75830218" ON "public"."auditlog_logentry" USING "btree" ("content_type_id");



CREATE INDEX "auditlog_logentry_object_id_09c2eee8" ON "public"."auditlog_logentry" USING "btree" ("object_id");



CREATE INDEX "auditlog_logentry_object_pk_6e3219c0" ON "public"."auditlog_logentry" USING "btree" ("object_pk");



CREATE INDEX "auditlog_logentry_object_pk_6e3219c0_like" ON "public"."auditlog_logentry" USING "btree" ("object_pk" "varchar_pattern_ops");



CREATE INDEX "auditlog_logentry_timestamp_37867bb0" ON "public"."auditlog_logentry" USING "btree" ("timestamp");



CREATE INDEX "auth_group_name_a6ea08ec_like" ON "public"."auth_group" USING "btree" ("name" "varchar_pattern_ops");



CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "public"."auth_group_permissions" USING "btree" ("group_id");



CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "public"."auth_group_permissions" USING "btree" ("permission_id");



CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "public"."auth_permission" USING "btree" ("content_type_id");



CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "public"."django_admin_log" USING "btree" ("content_type_id");



CREATE INDEX "django_admin_log_user_id_c564eba6" ON "public"."django_admin_log" USING "btree" ("user_id");



CREATE INDEX "django_seeding_appliedseeder_id_49695ba0_like" ON "public"."django_seeding_appliedseeder" USING "btree" ("id" "varchar_pattern_ops");



CREATE INDEX "django_session_expire_date_a5c62663" ON "public"."django_session" USING "btree" ("expire_date");



CREATE INDEX "django_session_session_key_c0390e0f_like" ON "public"."django_session" USING "btree" ("session_key" "varchar_pattern_ops");



CREATE INDEX "rental_card_form_id_e477f6cb" ON "public"."rental_card" USING "btree" ("form_id");



CREATE INDEX "rental_checkoption_field_id_2f5a7f6a" ON "public"."rental_checkoption" USING "btree" ("field_id");



CREATE INDEX "rental_client_email_d3b49dcd_like" ON "public"."rental_client" USING "btree" ("email" "varchar_pattern_ops");



CREATE INDEX "rental_client_phone_number_3be4620b_like" ON "public"."rental_client" USING "btree" ("phone_number" "varchar_pattern_ops");



CREATE INDEX "rental_client_tenant_id_80e06240" ON "public"."rental_client" USING "btree" ("tenant_id");



CREATE INDEX "rental_contract_client_id_be3512a6" ON "public"."rental_contract" USING "btree" ("client_id");



CREATE INDEX "rental_contract_rental_plan_id_be25643c" ON "public"."rental_contract" USING "btree" ("rental_plan_id");



CREATE INDEX "rental_contract_tenant_id_06fc9edf" ON "public"."rental_contract" USING "btree" ("tenant_id");



CREATE INDEX "rental_contract_vehicle_id_3a145b33" ON "public"."rental_contract" USING "btree" ("vehicle_id");



CREATE INDEX "rental_contractform_template_id_8e541966" ON "public"."rental_contractform" USING "btree" ("template_id");



CREATE INDEX "rental_contractform_tenant_id_d25aa087" ON "public"."rental_contractform" USING "btree" ("tenant_id");



CREATE INDEX "rental_contractform_user_id_af087fb1" ON "public"."rental_contractform" USING "btree" ("user_id");



CREATE INDEX "rental_contractformfield_template_id_4c53b3a6" ON "public"."rental_contractformfield" USING "btree" ("template_id");



CREATE INDEX "rental_contractformfieldresponse_field_id_185f276b" ON "public"."rental_contractformfieldresponse" USING "btree" ("field_id");



CREATE INDEX "rental_contractformfieldresponse_form_id_bd41d072" ON "public"."rental_contractformfieldresponse" USING "btree" ("form_id");



CREATE INDEX "rental_contractformtemplate_tenant_id_2437a7e8" ON "public"."rental_contractformtemplate" USING "btree" ("tenant_id");



CREATE INDEX "rental_contractformtemplate_user_id_09e0b3d4" ON "public"."rental_contractformtemplate" USING "btree" ("user_id");



CREATE INDEX "rental_field_card_id_70aedbd7" ON "public"."rental_field" USING "btree" ("card_id");



CREATE INDEX "rental_fieldresponse_check_option_id_00a413a8" ON "public"."rental_fieldresponse" USING "btree" ("check_option_selected_id");



CREATE INDEX "rental_fieldresponse_field_id_a56ab577" ON "public"."rental_fieldresponse" USING "btree" ("field_id");



CREATE INDEX "rental_fieldresponse_inspection_id_ed0fc9ed" ON "public"."rental_fieldresponse" USING "btree" ("inspection_id");



CREATE INDEX "rental_fieldresponse_tenantUser_id_f136f686" ON "public"."rental_fieldresponse" USING "btree" ("tenantUser_id");



CREATE INDEX "rental_form_tenant_id_305c23a4" ON "public"."rental_form" USING "btree" ("tenant_id");



CREATE INDEX "rental_inspection_form_id_23f25524" ON "public"."rental_inspection" USING "btree" ("form_id");



CREATE INDEX "rental_inspection_tenantUser_id_4e165641" ON "public"."rental_inspection" USING "btree" ("tenantUser_id");



CREATE INDEX "rental_inspection_tenant_id_b45c0c50" ON "public"."rental_inspection" USING "btree" ("tenant_id");



CREATE INDEX "rental_inspection_vehicle_id_07d3aa2e" ON "public"."rental_inspection" USING "btree" ("vehicle_id");



CREATE INDEX "rental_note_contract_id_501f4801" ON "public"."rental_note" USING "btree" ("contract_id");



CREATE INDEX "rental_note_user_id_beddd712" ON "public"."rental_note" USING "btree" ("user_id");



CREATE INDEX "rental_reminder_client_id_08ebe7de" ON "public"."rental_reminder" USING "btree" ("client_id");



CREATE INDEX "rental_reminder_contract_id_3d53b5cd" ON "public"."rental_reminder" USING "btree" ("contract_id");



CREATE INDEX "rental_reminder_created_by_id_d774a1cb" ON "public"."rental_reminder" USING "btree" ("created_by_id");



CREATE INDEX "rental_reminder_reminder_id_d2450d2d" ON "public"."rental_reminder" USING "btree" ("reminder_id");



CREATE INDEX "rental_reminder_toll_due_id_8b119779" ON "public"."rental_reminder" USING "btree" ("toll_due_id");



CREATE INDEX "rental_reminder_vehicle_id_ed9a6682" ON "public"."rental_reminder" USING "btree" ("vehicle_id");



CREATE INDEX "rental_rentalplan_tenant_id_b2956c0e" ON "public"."rental_rentalplan" USING "btree" ("tenant_id");



CREATE INDEX "rental_stageupdate_contract_id_2f8ce8b8" ON "public"."rental_stageupdate" USING "btree" ("contract_id");



CREATE INDEX "rental_tenant_email_9a596558_like" ON "public"."rental_tenant" USING "btree" ("email" "varchar_pattern_ops");



CREATE INDEX "rental_tenantuser_tenant_id_e03b8ebc" ON "public"."rental_tenantuser" USING "btree" ("tenant_id");



CREATE INDEX "rental_tenantuser_user_id_c91e0590" ON "public"."rental_tenantuser" USING "btree" ("user_id");



CREATE INDEX "rental_tolldue_contract_id_7d13ab5a" ON "public"."rental_tolldue" USING "btree" ("contract_id");



CREATE INDEX "rental_tolldue_plate_id_360832e5" ON "public"."rental_tolldue" USING "btree" ("plate_id");



CREATE INDEX "rental_trackerheartbeatdata_tracker_id_5152eac6" ON "public"."rental_trackerheartbeatdata" USING "btree" ("tracker_id");



CREATE INDEX "rental_user_email_51ab8052_like" ON "public"."rental_user" USING "btree" ("email" "varchar_pattern_ops");



CREATE INDEX "rental_user_groups_group_id_d2b2ecd2" ON "public"."rental_user_groups" USING "btree" ("group_id");



CREATE INDEX "rental_user_groups_user_id_40073f94" ON "public"."rental_user_groups" USING "btree" ("user_id");



CREATE INDEX "rental_user_user_permissions_permission_id_6b05905c" ON "public"."rental_user_user_permissions" USING "btree" ("permission_id");



CREATE INDEX "rental_user_user_permissions_user_id_99145fe1" ON "public"."rental_user_user_permissions" USING "btree" ("user_id");



CREATE INDEX "rental_vehicle_tenant_id_ea198a15" ON "public"."rental_vehicle" USING "btree" ("tenant_id");



CREATE INDEX "rental_vehicle_vin_40c1c227_like" ON "public"."rental_vehicle" USING "btree" ("vin" "varchar_pattern_ops");



CREATE INDEX "rental_vehiclepicture_vehicle_id_16c0d1dc" ON "public"."rental_vehiclepicture" USING "btree" ("vehicle_id");



CREATE INDEX "rental_vehicleplate_plate_07ffc9ac_like" ON "public"."rental_vehicleplate" USING "btree" ("plate" "varchar_pattern_ops");



CREATE INDEX "rental_vehicleplate_vehicle_id_7d0c9e03" ON "public"."rental_vehicleplate" USING "btree" ("vehicle_id");



CREATE INDEX "token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like" ON "public"."token_blacklist_outstandingtoken" USING "btree" ("jti" "varchar_pattern_ops");



CREATE INDEX "token_blacklist_outstandingtoken_user_id_83bc629a" ON "public"."token_blacklist_outstandingtoken" USING "btree" ("user_id");



ALTER TABLE ONLY "public"."auditlog_logentry"
    ADD CONSTRAINT "auditlog_logentry_actor_id_959271d2_fk_rental_user_id" FOREIGN KEY ("actor_id") REFERENCES "public"."rental_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auditlog_logentry"
    ADD CONSTRAINT "auditlog_logentry_content_type_id_75830218_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_permission"
    ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."django_admin_log"
    ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."django_admin_log"
    ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_rental_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."rental_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_card"
    ADD CONSTRAINT "rental_card_form_id_e477f6cb_fk_rental_form_id" FOREIGN KEY ("form_id") REFERENCES "public"."rental_form"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_checkoption"
    ADD CONSTRAINT "rental_checkoption_field_id_2f5a7f6a_fk_rental_field_id" FOREIGN KEY ("field_id") REFERENCES "public"."rental_field"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_client"
    ADD CONSTRAINT "rental_client_tenant_id_80e06240_fk_rental_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "public"."rental_tenant"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_contract"
    ADD CONSTRAINT "rental_contract_client_id_be3512a6_fk_rental_client_id" FOREIGN KEY ("client_id") REFERENCES "public"."rental_client"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_contract"
    ADD CONSTRAINT "rental_contract_rental_plan_id_be25643c_fk_rental_rentalplan_id" FOREIGN KEY ("rental_plan_id") REFERENCES "public"."rental_rentalplan"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_contract"
    ADD CONSTRAINT "rental_contract_tenant_id_06fc9edf_fk_rental_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "public"."rental_tenant"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_contract"
    ADD CONSTRAINT "rental_contract_vehicle_id_3a145b33_fk_rental_vehicle_id" FOREIGN KEY ("vehicle_id") REFERENCES "public"."rental_vehicle"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_contractform"
    ADD CONSTRAINT "rental_contractform_template_id_8e541966_fk_rental_co" FOREIGN KEY ("template_id") REFERENCES "public"."rental_contractformtemplate"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_contractform"
    ADD CONSTRAINT "rental_contractform_tenant_id_d25aa087_fk_rental_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "public"."rental_tenant"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_contractform"
    ADD CONSTRAINT "rental_contractform_user_id_af087fb1_fk_rental_tenantuser_id" FOREIGN KEY ("user_id") REFERENCES "public"."rental_tenantuser"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_contractformfieldresponse"
    ADD CONSTRAINT "rental_contractformf_field_id_185f276b_fk_rental_co" FOREIGN KEY ("field_id") REFERENCES "public"."rental_contractformfield"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_contractformfieldresponse"
    ADD CONSTRAINT "rental_contractformf_form_id_bd41d072_fk_rental_co" FOREIGN KEY ("form_id") REFERENCES "public"."rental_contractform"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_contractformfield"
    ADD CONSTRAINT "rental_contractformf_template_id_4c53b3a6_fk_rental_co" FOREIGN KEY ("template_id") REFERENCES "public"."rental_contractformtemplate"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_contractformtemplate"
    ADD CONSTRAINT "rental_contractformt_tenant_id_2437a7e8_fk_rental_te" FOREIGN KEY ("tenant_id") REFERENCES "public"."rental_tenant"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_contractformtemplate"
    ADD CONSTRAINT "rental_contractformt_user_id_09e0b3d4_fk_rental_te" FOREIGN KEY ("user_id") REFERENCES "public"."rental_tenantuser"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_field"
    ADD CONSTRAINT "rental_field_card_id_70aedbd7_fk_rental_card_id" FOREIGN KEY ("card_id") REFERENCES "public"."rental_card"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_fieldresponse"
    ADD CONSTRAINT "rental_fieldresponse_check_option_selecte_9dc80a21_fk_rental_ch" FOREIGN KEY ("check_option_selected_id") REFERENCES "public"."rental_checkoption"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_fieldresponse"
    ADD CONSTRAINT "rental_fieldresponse_field_id_a56ab577_fk_rental_field_id" FOREIGN KEY ("field_id") REFERENCES "public"."rental_field"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_fieldresponse"
    ADD CONSTRAINT "rental_fieldresponse_inspection_id_ed0fc9ed_fk_rental_in" FOREIGN KEY ("inspection_id") REFERENCES "public"."rental_inspection"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_fieldresponse"
    ADD CONSTRAINT "rental_fieldresponse_tenantUser_id_f136f686_fk_rental_te" FOREIGN KEY ("tenantUser_id") REFERENCES "public"."rental_tenantuser"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_form"
    ADD CONSTRAINT "rental_form_tenant_id_305c23a4_fk_rental_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "public"."rental_tenant"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_inspection"
    ADD CONSTRAINT "rental_inspection_form_id_23f25524_fk_rental_form_id" FOREIGN KEY ("form_id") REFERENCES "public"."rental_form"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_inspection"
    ADD CONSTRAINT "rental_inspection_tenantUser_id_4e165641_fk_rental_te" FOREIGN KEY ("tenantUser_id") REFERENCES "public"."rental_tenantuser"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_inspection"
    ADD CONSTRAINT "rental_inspection_tenant_id_b45c0c50_fk_rental_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "public"."rental_tenant"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_inspection"
    ADD CONSTRAINT "rental_inspection_vehicle_id_07d3aa2e_fk_rental_vehicle_id" FOREIGN KEY ("vehicle_id") REFERENCES "public"."rental_vehicle"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_note"
    ADD CONSTRAINT "rental_note_contract_id_501f4801_fk_rental_contract_id" FOREIGN KEY ("contract_id") REFERENCES "public"."rental_contract"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_note"
    ADD CONSTRAINT "rental_note_user_id_beddd712_fk_rental_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."rental_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_reminder"
    ADD CONSTRAINT "rental_reminder_client_id_08ebe7de_fk_rental_client_id" FOREIGN KEY ("client_id") REFERENCES "public"."rental_client"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_reminder"
    ADD CONSTRAINT "rental_reminder_contract_id_3d53b5cd_fk_rental_contract_id" FOREIGN KEY ("contract_id") REFERENCES "public"."rental_contract"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_reminder"
    ADD CONSTRAINT "rental_reminder_created_by_id_d774a1cb_fk_rental_tenantuser_id" FOREIGN KEY ("created_by_id") REFERENCES "public"."rental_tenantuser"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_reminder"
    ADD CONSTRAINT "rental_reminder_reminder_id_d2450d2d_fk_rental_reminder_id" FOREIGN KEY ("reminder_id") REFERENCES "public"."rental_reminder"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_reminder"
    ADD CONSTRAINT "rental_reminder_toll_due_id_8b119779_fk_rental_tolldue_id" FOREIGN KEY ("toll_due_id") REFERENCES "public"."rental_tolldue"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_reminder"
    ADD CONSTRAINT "rental_reminder_vehicle_id_ed9a6682_fk_rental_vehicle_id" FOREIGN KEY ("vehicle_id") REFERENCES "public"."rental_vehicle"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_rentalplan"
    ADD CONSTRAINT "rental_rentalplan_tenant_id_b2956c0e_fk_rental_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "public"."rental_tenant"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_stageupdate"
    ADD CONSTRAINT "rental_stageupdate_contract_id_2f8ce8b8_fk_rental_contract_id" FOREIGN KEY ("contract_id") REFERENCES "public"."rental_contract"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_tenantuser"
    ADD CONSTRAINT "rental_tenantuser_tenant_id_e03b8ebc_fk_rental_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "public"."rental_tenant"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_tenantuser"
    ADD CONSTRAINT "rental_tenantuser_user_id_c91e0590_fk_rental_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."rental_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_tolldue"
    ADD CONSTRAINT "rental_tolldue_contract_id_7d13ab5a_fk_rental_contract_id" FOREIGN KEY ("contract_id") REFERENCES "public"."rental_contract"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_tolldue"
    ADD CONSTRAINT "rental_tolldue_plate_id_360832e5_fk_rental_vehicleplate_id" FOREIGN KEY ("plate_id") REFERENCES "public"."rental_vehicleplate"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_tracker"
    ADD CONSTRAINT "rental_tracker_vehicle_id_49a19b0e_fk_rental_vehicle_id" FOREIGN KEY ("vehicle_id") REFERENCES "public"."rental_vehicle"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_trackerheartbeatdata"
    ADD CONSTRAINT "rental_trackerheartb_tracker_id_5152eac6_fk_rental_tr" FOREIGN KEY ("tracker_id") REFERENCES "public"."rental_tracker"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_user_groups"
    ADD CONSTRAINT "rental_user_groups_group_id_d2b2ecd2_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_user_groups"
    ADD CONSTRAINT "rental_user_groups_user_id_40073f94_fk_rental_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."rental_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_user_user_permissions"
    ADD CONSTRAINT "rental_user_user_per_permission_id_6b05905c_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_user_user_permissions"
    ADD CONSTRAINT "rental_user_user_permissions_user_id_99145fe1_fk_rental_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."rental_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_vehicle"
    ADD CONSTRAINT "rental_vehicle_tenant_id_ea198a15_fk_rental_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "public"."rental_tenant"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_vehiclepicture"
    ADD CONSTRAINT "rental_vehiclepicture_vehicle_id_16c0d1dc_fk_rental_vehicle_id" FOREIGN KEY ("vehicle_id") REFERENCES "public"."rental_vehicle"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."rental_vehicleplate"
    ADD CONSTRAINT "rental_vehicleplate_vehicle_id_7d0c9e03_fk_rental_vehicle_id" FOREIGN KEY ("vehicle_id") REFERENCES "public"."rental_vehicle"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."token_blacklist_blacklistedtoken"
    ADD CONSTRAINT "token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk" FOREIGN KEY ("token_id") REFERENCES "public"."token_blacklist_outstandingtoken"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."token_blacklist_outstandingtoken"
    ADD CONSTRAINT "token_blacklist_outs_user_id_83bc629a_fk_rental_us" FOREIGN KEY ("user_id") REFERENCES "public"."rental_user"("id") DEFERRABLE INITIALLY DEFERRED;





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



































































































































































































GRANT ALL ON TABLE "public"."auditlog_logentry" TO "anon";
GRANT ALL ON TABLE "public"."auditlog_logentry" TO "authenticated";
GRANT ALL ON TABLE "public"."auditlog_logentry" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auditlog_logentry_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auditlog_logentry_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auditlog_logentry_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."auth_group" TO "anon";
GRANT ALL ON TABLE "public"."auth_group" TO "authenticated";
GRANT ALL ON TABLE "public"."auth_group" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_group_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_group_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_group_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."auth_group_permissions" TO "anon";
GRANT ALL ON TABLE "public"."auth_group_permissions" TO "authenticated";
GRANT ALL ON TABLE "public"."auth_group_permissions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_group_permissions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_group_permissions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_group_permissions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."auth_permission" TO "anon";
GRANT ALL ON TABLE "public"."auth_permission" TO "authenticated";
GRANT ALL ON TABLE "public"."auth_permission" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_permission_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_permission_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_permission_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."django_admin_log" TO "anon";
GRANT ALL ON TABLE "public"."django_admin_log" TO "authenticated";
GRANT ALL ON TABLE "public"."django_admin_log" TO "service_role";



GRANT ALL ON SEQUENCE "public"."django_admin_log_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."django_admin_log_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."django_admin_log_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."django_content_type" TO "anon";
GRANT ALL ON TABLE "public"."django_content_type" TO "authenticated";
GRANT ALL ON TABLE "public"."django_content_type" TO "service_role";



GRANT ALL ON SEQUENCE "public"."django_content_type_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."django_content_type_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."django_content_type_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."django_migrations" TO "anon";
GRANT ALL ON TABLE "public"."django_migrations" TO "authenticated";
GRANT ALL ON TABLE "public"."django_migrations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."django_migrations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."django_migrations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."django_migrations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."django_seeding_appliedseeder" TO "anon";
GRANT ALL ON TABLE "public"."django_seeding_appliedseeder" TO "authenticated";
GRANT ALL ON TABLE "public"."django_seeding_appliedseeder" TO "service_role";



GRANT ALL ON TABLE "public"."django_session" TO "anon";
GRANT ALL ON TABLE "public"."django_session" TO "authenticated";
GRANT ALL ON TABLE "public"."django_session" TO "service_role";



GRANT ALL ON TABLE "public"."rental_card" TO "anon";
GRANT ALL ON TABLE "public"."rental_card" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_card" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_card_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_card_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_card_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_checkoption" TO "anon";
GRANT ALL ON TABLE "public"."rental_checkoption" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_checkoption" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_checkoption_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_checkoption_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_checkoption_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_client" TO "anon";
GRANT ALL ON TABLE "public"."rental_client" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_client" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_client_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_client_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_client_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_contract" TO "anon";
GRANT ALL ON TABLE "public"."rental_contract" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_contract" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_contract_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_contract_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_contract_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_contractform" TO "anon";
GRANT ALL ON TABLE "public"."rental_contractform" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_contractform" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_contractform_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_contractform_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_contractform_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_contractformfield" TO "anon";
GRANT ALL ON TABLE "public"."rental_contractformfield" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_contractformfield" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_contractformfield_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_contractformfield_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_contractformfield_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_contractformfieldresponse" TO "anon";
GRANT ALL ON TABLE "public"."rental_contractformfieldresponse" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_contractformfieldresponse" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_contractformfieldresponse_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_contractformfieldresponse_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_contractformfieldresponse_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_contractformtemplate" TO "anon";
GRANT ALL ON TABLE "public"."rental_contractformtemplate" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_contractformtemplate" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_contractformtemplate_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_contractformtemplate_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_contractformtemplate_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_field" TO "anon";
GRANT ALL ON TABLE "public"."rental_field" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_field" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_field_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_field_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_field_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_fieldresponse" TO "anon";
GRANT ALL ON TABLE "public"."rental_fieldresponse" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_fieldresponse" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_fieldresponse_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_fieldresponse_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_fieldresponse_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_form" TO "anon";
GRANT ALL ON TABLE "public"."rental_form" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_form" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_form_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_form_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_form_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_inspection" TO "anon";
GRANT ALL ON TABLE "public"."rental_inspection" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_inspection" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_inspection_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_inspection_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_inspection_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_note" TO "anon";
GRANT ALL ON TABLE "public"."rental_note" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_note" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_note_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_note_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_note_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_reminder" TO "anon";
GRANT ALL ON TABLE "public"."rental_reminder" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_reminder" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_reminder_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_reminder_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_reminder_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_rentalplan" TO "anon";
GRANT ALL ON TABLE "public"."rental_rentalplan" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_rentalplan" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_rentalplan_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_rentalplan_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_rentalplan_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_stageupdate" TO "anon";
GRANT ALL ON TABLE "public"."rental_stageupdate" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_stageupdate" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_stageupdate_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_stageupdate_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_stageupdate_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_tenant" TO "anon";
GRANT ALL ON TABLE "public"."rental_tenant" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_tenant" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_tenant_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_tenant_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_tenant_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_tenantuser" TO "anon";
GRANT ALL ON TABLE "public"."rental_tenantuser" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_tenantuser" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_tenantuser_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_tenantuser_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_tenantuser_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_tolldue" TO "anon";
GRANT ALL ON TABLE "public"."rental_tolldue" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_tolldue" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_tolldue_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_tolldue_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_tolldue_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_tracker" TO "anon";
GRANT ALL ON TABLE "public"."rental_tracker" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_tracker" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_tracker_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_tracker_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_tracker_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_trackerheartbeatdata" TO "anon";
GRANT ALL ON TABLE "public"."rental_trackerheartbeatdata" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_trackerheartbeatdata" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_trackerheartbeatdata_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_trackerheartbeatdata_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_trackerheartbeatdata_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_user" TO "anon";
GRANT ALL ON TABLE "public"."rental_user" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_user" TO "service_role";



GRANT ALL ON TABLE "public"."rental_user_groups" TO "anon";
GRANT ALL ON TABLE "public"."rental_user_groups" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_user_groups" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_user_groups_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_user_groups_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_user_groups_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_user_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_user_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_user_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_user_user_permissions" TO "anon";
GRANT ALL ON TABLE "public"."rental_user_user_permissions" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_user_user_permissions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_user_user_permissions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_user_user_permissions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_user_user_permissions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_vehicle" TO "anon";
GRANT ALL ON TABLE "public"."rental_vehicle" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_vehicle" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_vehicle_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_vehicle_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_vehicle_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_vehiclepicture" TO "anon";
GRANT ALL ON TABLE "public"."rental_vehiclepicture" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_vehiclepicture" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_vehiclepicture_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_vehiclepicture_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_vehiclepicture_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rental_vehicleplate" TO "anon";
GRANT ALL ON TABLE "public"."rental_vehicleplate" TO "authenticated";
GRANT ALL ON TABLE "public"."rental_vehicleplate" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rental_vehicleplate_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rental_vehicleplate_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rental_vehicleplate_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."token_blacklist_blacklistedtoken" TO "anon";
GRANT ALL ON TABLE "public"."token_blacklist_blacklistedtoken" TO "authenticated";
GRANT ALL ON TABLE "public"."token_blacklist_blacklistedtoken" TO "service_role";



GRANT ALL ON SEQUENCE "public"."token_blacklist_blacklistedtoken_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."token_blacklist_blacklistedtoken_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."token_blacklist_blacklistedtoken_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."token_blacklist_outstandingtoken" TO "anon";
GRANT ALL ON TABLE "public"."token_blacklist_outstandingtoken" TO "authenticated";
GRANT ALL ON TABLE "public"."token_blacklist_outstandingtoken" TO "service_role";



GRANT ALL ON SEQUENCE "public"."token_blacklist_outstandingtoken_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."token_blacklist_outstandingtoken_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."token_blacklist_outstandingtoken_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
