# Generated by Django 5.0.2 on 2024-04-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0002_user_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
    ]
