# Generated by Django 5.0.2 on 2024-04-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0010_alter_customuser_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
