# Generated by Django 5.0.2 on 2024-04-29 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0011_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="rental.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="tenantuser",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenantUsers",
                to="rental.tenant",
            ),
        ),
    ]
