# Generated by Django 5.0.2 on 2024-04-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0012_alter_client_tenant_alter_tenantuser_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="date_joined",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
