# Generated by Django 5.0.2 on 2024-05-01 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0013_tenant_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ATV', 'ATV'), ('Boat', 'Boat'), ('Bus', 'Bus'), ('Car', 'Car'), ('Chassis', 'Chassis'), ('Equipment', 'Equipment'), ('Forklift', 'Forklift'), ('Freightliner', 'Freightliner'), ('Generator', 'Generator'), ('Machinery', 'Machinery'), ('Motorcycle', 'Motorcycle'), ('Plane', 'Plane'), ('RV', 'Recreational Vehicle'), ('SUV', 'Sport Utility Vehicle'), ('Tractor', 'Tractor'), ('Trailer', 'Trailer'), ('Truck', 'Truck'), ('Van', 'Van'), ('Custom', 'Custom')])),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('trim', models.CharField(max_length=255)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('odometer', models.IntegerField()),
                ('nickname', models.CharField(max_length=255)),
                ('spare_tires', models.IntegerField(default=0)),
                ('extra_fields', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')])),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePicture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=255)),
                ('pinned', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_pictures', to='rental.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('plate', models.CharField(max_length=255, unique=True)),
                ('assign_date', models.DateTimeField(auto_now_add=True)),
                ('dismiss_date', models.DateTimeField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plates', to='rental.vehicle')),
            ],
        ),
    ]
