# Generated by Django 5.0.2 on 2024-05-01 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0014_vehicle_vehiclepicture_vehicleplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicles",
                to="rental.tenant",
            ),
        ),
    ]
