# Generated by Django 5.0.2 on 2024-05-01 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0015_vehicle_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='rental.tenant'),
        ),
    ]
