# Generated by Django 5.0.2 on 2024-05-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0019_alter_stageupdate_previous_stage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stageupdate",
            options={"ordering": ["date"]},
        ),
        migrations.RemoveField(
            model_name="stageupdate",
            name="previous_stage",
        ),
    ]
