# Generated by Django 5.0.2 on 2024-05-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0028_alter_rentalplan_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('Car', 'Car'), ('Freightliner', 'Freightliner'), ('SUV', 'Sport Utility Vehicle'), ('Trailer', 'Trailer'), ('Truck', 'Truck'), ('Van', 'Van'), ('Custom', 'Custom')]),
        ),
    ]
