# Generated by Django 5.0.2 on 2024-05-21 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0028_alter_rentalplan_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="type",
            field=models.CharField(
                choices=[
                    ("Car", "Car"),
                    ("Freightliner", "Freightliner"),
                    ("SUV", "Sport Utility Vehicle"),
                    ("Trailer", "Trailer"),
                    ("Truck", "Truck"),
                    ("Van", "Van"),
                    ("Custom", "Custom"),
                ]
            ),
        ),
        migrations.AlterModelOptions(
            name="form",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterField(
            model_name="card",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to="rental.form",
            ),
        ),
        migrations.AlterField(
            model_name="fieldresponse",
            name="check_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="response",
                to="rental.checkoption",
            ),
        ),
    ]
