# Generated by Django 5.0.2 on 2024-06-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0029_alter_form_options_alter_card_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('SINGLE_CHECK', 'Single Check'), ('IMAGE', 'Image'), ('SIGNATURE', 'Signature'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('DATE', 'Date'), ('TIME', 'Time')], max_length=20),
        ),
    ]
