# Generated by Django 5.0.2 on 2024-05-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0030_alter_vehicle_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="model",
        ),
        migrations.AlterModelOptions(
            name="form",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="checkoption",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEFAULT", "default"),
                    ("POINT_PASS", "Point pass"),
                    ("POINT_FAIL", "Point fail"),
                ],
                default="DEFAULT",
                max_length=20,
            ),
        ),
    ]
