# Generated by Django 5.0.2 on 2024-05-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0030_alter_vehicle_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="model",
        ),
    ]
