# Generated by Django 5.0.2 on 2024-05-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0031_remove_vehicle_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stageupdate',
            options={'ordering': ['-date'], 'verbose_name': 'Stage', 'verbose_name_plural': 'Stages'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
