# Generated by Django 5.0.2 on 2024-05-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0032_alter_stageupdate_options_vehicle_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
