# Generated by Django 5.0.2 on 2024-05-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0034_alter_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('Car', 'Car'), ('SUV', 'SUV'), ('Freightliner', 'Freightliner'), ('Trailer', 'Trailer'), ('Truck', 'Truck'), ('Van', 'Van'), ('Custom', 'Custom')]),
        ),
    ]
