# Generated by Django 5.0.2 on 2024-06-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0037_alter_vehicle_odometer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='spare_tires',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
