# Generated by Django 5.0.2 on 2024-06-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0040_alter_field_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="form",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="checkoption",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEFAULT", "default"),
                    ("POINT_PASS", "Point pass"),
                    ("POINT_FAIL", "Point fail"),
                ],
                default="DEFAULT",
                max_length=20,
            ),
        ),
    ]
