# Generated by Django 5.0.2 on 2024-06-15 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0041_alter_form_options_checkoption_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ['created_at']},
        ),
    ]
