# Generated by Django 5.0.2 on 2024-06-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0043_remove_fieldresponse_checked_alter_note_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldresponse',
            old_name='check_option',
            new_name='check_option_selected',
        ),
    ]
