# Generated by Django 5.0.2 on 2024-07-25 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0044_rename_check_option_fieldresponse_check_option_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.tenantuser')),
            ],
        ),
    ]
