# Generated by Django 5.0.2 on 2024-07-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0045_contractformtemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractformtemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='contractformtemplate',
            name='template',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
