# Generated by Django 5.0.2 on 2024-07-29 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0046_alter_contractformtemplate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.contractformtemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.tenantuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
