# Generated by Django 5.0.2 on 2024-07-31 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0048_alter_contractform_template_contractformfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractformfield',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='contractformfield',
            name='user',
        ),
    ]
