# Generated by Django 5.0.2 on 2024-08-02 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0049_remove_contractformfield_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractFormFieldResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.contractformfield')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.contractform')),
            ],
        ),
    ]
