# Generated by Django 5.0.2 on 2024-08-05 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0050_contractformfieldresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractformfieldresponse',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='rental.contractform'),
        ),
    ]
