# Generated by Django 5.0.2 on 2024-08-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0051_alter_contractformfieldresponse_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractformtemplate',
            name='html_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
