# Generated by Django 5.0.2 on 2024-10-28 18:13

import django.db.models.deletion
import rental.reminders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0051_alter_contractformfieldresponse_form"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Waiting", "Waiting"),
                            ("In progress", "In progress"),
                            ("Completed", "Completed"),
                            ("Incomplete", "Incomplete"),
                        ],
                        default="Waiting",
                        max_length=50,
                    ),
                ),
                ("important", models.BooleanField(default=False)),
                ("title", models.TextField()),
                ("content", models.TextField(null=True)),
                ("remainder", models.DateTimeField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=rental.reminders.models.get_file_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="rental.client",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="rental.contract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="my_reminders",
                        to="rental.tenantuser",
                    ),
                ),
                (
                    "toll_due",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="rental.tolldue",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="rental.vehicle",
                    ),
                ),
            ],
        ),
    ]
