# Generated by Django 5.0.2 on 2024-10-30 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0052_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="reminder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="rental.reminder",
            ),
        ),
    ]
