# Generated by Django 5.0.2 on 2024-11-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0053_reminder_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractformtemplate',
            name='html_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
