name: Deploy

on:
  workflow_dispatch:

jobs:
  production:
    runs-on: ubuntu-latest
    environment:
      name: deployment
      url: https://app.towitrentals.com/admin/
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H 154.53.40.104 >> ~/.ssh/known_hosts
      - name: work in remote server
        run: |
          ssh ${{ secrets.USER_IP_16 }} "./Rental/rental_backend/rebuild_and_run.sh"